name: PR Check
on: [pull_request]
jobs:
  test:
    runs-on: self-hosted
    container:
      image: winamd64/python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: python setup
        run: |
          pip install poetry==1.4.2
          python3 -m poetry install --with dev
      - name:  format check 
        run: |
            poetry run black --check .
            poetry run isort --check .
      - name: dependency check
        run: |
            poetry run deptry .
      - name: pytest
        run: |
            poetry run pytest --cov-report term --cov-report html --cov=./runefumbler .
      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
      
      
      
    
